/**
 * Order models for the CRM system.
 *
 * Orders are the central entity of the CRM. Total amounts (totalHt, totalTtc)
 * are calculated on the frontend before sending to the API.
 *
 * @category Models
 */

export interface Order {
  id?: number;
  customer: string;
  nbDays: number;
  tjm: number;
  tauxTva: number;
}


/**
 * Represents an order in the CRM system.
 *
 * Orders contain customer information, project details (days, daily rate),
 * tax information, and calculated totals.
 *
 * @category Models
 */
export interface OrderDetail extends Order {


  /**
   * Total amount excluding VAT (HT - Hors Taxes)
   * Calculated as: nbDays * tjm
   * @required
   * @readonly - Calculated automatically on frontend
   */
  totalHt: number;

  /**
   * Total amount including VAT (TTC - Toutes Taxes Comprises)
   * Calculated as: totalHt * (1 + tauxTva / 100)
   * @required
   * @readonly - Calculated automatically on frontend
   */
  totalTtc: number;
}

/**
 * Payload for creating a new order.
 *
 * Excludes `id` (generated by json-server) and calculated totals
 * (`totalHt`, `totalTtc`) which are computed on the frontend before sending.
 *
 * @category Models
 * @see OrderDetail
 */
export type CreateOrder = Order;
/**
 * Payload for updating an existing order.
 *
 * Excludes calculated totals (`totalHt`, `totalTtc`) which are computed
 * on the frontend before sending. The `id` is required to identify the order.
 *
 * @category Models
 * @see OrderDetail
 */
export type UpdateOrder = Order;